int a = 2;
Console.WriteLine(a*1);
Console.WriteLine(a*2);
Console.WriteLine(a*3);
Console.WriteLine(a*4);
Console.WriteLine(a*5);
Console.WriteLine(a*6);
Console.WriteLine(a*7);
Console.WriteLine(a*8);
Console.WriteLine(a*9);
Console.WriteLine(a*10);